services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - RUN_SCRIPT=bot.py
    depends_on:
      - ollama
    networks:
      - app_network

  miniapp:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - RUN_SCRIPT=app.py
    depends_on:
      - ollama
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_volume:/root/.ollama  # Persistent storage for models
    environment:
      - OLLAMA_PULL_MODELS=llama3.2:3b qwen2.5-coder:32b llama3.2-vision:11b
    entrypoint: /bin/bash
    command: -xec "/bin/ollama serve & for m in $$OLLAMA_PULL_MODELS; do /bin/ollama pull $${m}; done; wait"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./static:/app/static
    depends_on:
      - miniapp
    restart: unless-stopped
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email admin@flights-reminder.com -d flights-reminder.com --agree-tos
    depends_on:
      - nginx
    networks:
      - app_network

volumes:
  ollama_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/src/ollama/storage

networks:
  app_network:
    driver: bridge
