server {
    listen 443 ssl;
    server_name flights-reminder.com;

    # SSL configuration
    ssl_certificate /etc/letsencrypt/live/flights-reminder.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flights-reminder.com/privkey.pem;
    
    # SSL parameters
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security "max-age=31536000" always;

    # Root directory for static files

    # Handle static files
    location /static/ {
        root /app;
        # First attempt to serve static files directly
        try_files $uri =404;
        
        # Common settings for static files
        access_log off;
        expires 30d;
        add_header Cache-Control "public, no-transform";

        # Set proper content types based on file extensions
        location ~* \.(?:jpg|jpeg)$ {
            add_header Content-Type image/jpeg;
        }
        location ~* \.svg$ {
            add_header Content-Type image/svg+xml;
        }
        location ~* \.ico$ {
            add_header Content-Type image/x-icon;
        }
        location ~* \.html$ {
            add_header Content-Type text/html;
        }
    }

    # Special handling for manifest file
    location = /tonconnect-manifest.json {
        try_files /static/tonconnect-manifest.json =404;
        add_header Content-Type application/json;
    }

    # Handle root path - proxy to Flask app
    location / {
        proxy_pass http://miniapp:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
} 